//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAG_Login_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.Pages1 = new HashSet<Page>();
        }
    
        public int Id { get; set; }
        public string PageName { get; set; }
        public Nullable<System.Guid> PageId { get; set; }
        public int SiteId { get; set; }
        public string IsFirstTime { get; set; }
        public Nullable<int> ParentPageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages1 { get; set; }
        public virtual Page Page1 { get; set; }
        public virtual Site Site { get; set; }
    }
}
