//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppGoTypeScript_X_Modulerization.ImageServiceAgent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageJQ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ImageJQ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageServiceAgent.ImageServiceSoap")]
    public interface ImageServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponse HelloWorld(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponse> HelloWorldAsync(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetImagesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImages", ReplyAction="*")]
        WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponse GetImages(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImages", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponse> GetImagesAsync(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImages", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequestBody Body;
        
        public GetImagesRequest() {
        }
        
        public GetImagesRequest(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetImagesRequestBody {
        
        public GetImagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponseBody Body;
        
        public GetImagesResponse() {
        }
        
        public GetImagesResponse(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageJQ[] GetImagesResult;
        
        public GetImagesResponseBody() {
        }
        
        public GetImagesResponseBody(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageJQ[] GetImagesResult) {
            this.GetImagesResult = GetImagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageServiceSoapChannel : WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceSoapClient : System.ServiceModel.ClientBase<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap>, WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap {
        
        public ImageServiceSoapClient() {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponse WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap.HelloWorld(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest inValue = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequestBody();
            WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponse retVal = ((WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponse> WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap.HelloWorldAsync(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldResponse> HelloWorldAsync() {
            WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest inValue = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.HelloWorldRequestBody();
            return ((WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponse WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap.GetImages(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest request) {
            return base.Channel.GetImages(request);
        }
        
        public WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageJQ[] GetImages() {
            WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest inValue = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequestBody();
            WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponse retVal = ((WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap)(this)).GetImages(inValue);
            return retVal.Body.GetImagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponse> WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap.GetImagesAsync(WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest request) {
            return base.Channel.GetImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesResponse> GetImagesAsync() {
            WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest inValue = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.GetImagesRequestBody();
            return ((WebAppGoTypeScript_X_Modulerization.ImageServiceAgent.ImageServiceSoap)(this)).GetImagesAsync(inValue);
        }
    }
}
