var jQuery = {
  "fn": {},
  "extend": function () {},
  "expando": {},
  "isReady": {},
  "error": function () {},
  "noop": function () {},
  "isFunction": function () {},
  "isArray": function () {},
  "isWindow": function () {},
  "isNumeric": function () {},
  "isEmptyObject": function () {},
  "isPlainObject": function () {},
  "type": function () {},
  "globalEval": function () {},
  "camelCase": function () {},
  "nodeName": function () {},
  "each": function () {},
  "trim": function () {},
  "makeArray": function () {},
  "inArray": function () {},
  "merge": function () {},
  "grep": function () {},
  "map": function () {},
  "guid": {},
  "proxy": function () {},
  "now": function () {},
  "support": {},
  "find": {
    "support": {},
    "isXML": function () {},
    "setDocument": function () {},
    "matches": function () {},
    "matchesSelector": function () {},
    "contains": function () {},
    "attr": function () {},
    "error": function () {},
    "uniqueSort": function () {},
    "getText": function () {},
    "selectors": {},
    "tokenize": function () {},
    "compile": function () {},
    "select": function () {}
  },
  "expr": {},
  "unique": function () {},
  "text": function () {},
  "isXMLDoc": function () {},
  "contains": function () {},
  "filter": function () {},
  "dir": function () {},
  "sibling": function () {},
  "Callbacks": function () {},
  "Deferred": function () {},
  "when": function () {},
  "readyWait": {},
  "holdReady": function () {},
  "ready": {
    "promise": function () {}
  },
  "acceptData": function () {},
  "cache": {},
  "noData": {},
  "hasData": function () {},
  "data": function () {},
  "removeData": function () {},
  "_data": function () {},
  "_removeData": function () {},
  "queue": function () {},
  "dequeue": function () {},
  "_queueHooks": function () {},
  "access": function () {},
  "event": {},
  "removeEvent": function () {},
  "Event": function () {},
  "clone": function () {},
  "buildFragment": function () {},
  "cleanData": function () {},
  "swap": function () {},
  "cssHooks": {},
  "cssNumber": {},
  "cssProps": {},
  "style": function () {},
  "css": function () {},
  "Tween": {
    "propHooks": {}
  },
  "easing": {},
  "fx": {
    "step": {},
    "tick": function () {},
    "timer": function () {},
    "interval": {},
    "start": function () {},
    "stop": function () {},
    "speeds": {}
  },
  "Animation": {
    "tweener": function () {},
    "prefilter": function () {}
  },
  "speed": function () {},
  "timers": {},
  "valHooks": {},
  "attr": function () {},
  "removeAttr": function () {},
  "attrHooks": {},
  "propFix": {},
  "prop": function () {},
  "propHooks": {},
  "parseJSON": function () {},
  "parseXML": function () {},
  "active": {},
  "lastModified": {},
  "etag": {},
  "ajaxSettings": {},
  "ajaxSetup": function () {},
  "ajaxPrefilter": function () {},
  "ajaxTransport": function () {},
  "ajax": function () {},
  "getJSON": function () {},
  "getScript": function () {},
  "get": function () {},
  "post": function () {},
  "_evalUrl": function () {},
  "param": function () {},
  "parseHTML": function () {},
  "offset": {},
  "noConflict": function () {}
};
jQuery.prototype = {
  "jquery": function () {},
  "constructor": function () {},
  "selector": function () {},
  "length": function () {},
  "toArray": function () {},
  "get": function () {},
  "pushStack": function () {},
  "each": function () {},
  "map": function () {},
  "slice": function () {},
  "first": function () {},
  "last": function () {},
  "eq": function () {},
  "end": function () {},
  "push": function () {},
  "sort": function () {},
  "splice": function () {},
  "extend": function () {},
  "find": function () {},
  "filter": function () {},
  "not": function () {},
  "is": function () {},
  "init": function () {},
  "has": function () {},
  "closest": function () {},
  "index": function () {},
  "add": function () {},
  "addBack": function () {},
  "parent": function () {},
  "parents": function () {},
  "parentsUntil": function () {},
  "next": function () {},
  "prev": function () {},
  "nextAll": function () {},
  "prevAll": function () {},
  "nextUntil": function () {},
  "prevUntil": function () {},
  "siblings": function () {},
  "children": function () {},
  "contents": function () {},
  "ready": function () {},
  "data": function () {},
  "removeData": function () {},
  "queue": function () {},
  "dequeue": function () {},
  "clearQueue": function () {},
  "promise": function () {},
  "on": function () {},
  "one": function () {},
  "off": function () {},
  "trigger": function () {},
  "triggerHandler": function () {},
  "text": function () {},
  "append": function () {},
  "prepend": function () {},
  "before": function () {},
  "after": function () {},
  "remove": function () {},
  "empty": function () {},
  "clone": function () {},
  "html": function () {},
  "replaceWith": function () {},
  "detach": function () {},
  "domManip": function () {},
  "appendTo": function () {},
  "prependTo": function () {},
  "insertBefore": function () {},
  "insertAfter": function () {},
  "replaceAll": function () {},
  "css": function () {},
  "show": function () {},
  "hide": function () {},
  "toggle": function () {},
  "fadeTo": function () {},
  "animate": function () {},
  "stop": function () {},
  "finish": function () {},
  "slideDown": function () {},
  "slideUp": function () {},
  "slideToggle": function () {},
  "fadeIn": function () {},
  "fadeOut": function () {},
  "fadeToggle": function () {},
  "delay": function () {},
  "val": function () {},
  "attr": function () {},
  "removeAttr": function () {},
  "prop": function () {},
  "removeProp": function () {},
  "addClass": function () {},
  "removeClass": function () {},
  "toggleClass": function () {},
  "hasClass": function () {},
  "blur": function () {},
  "focus": function () {},
  "focusin": function () {},
  "focusout": function () {},
  "load": function () {},
  "resize": function () {},
  "scroll": function () {},
  "unload": function () {},
  "click": function () {},
  "dblclick": function () {},
  "mousedown": function () {},
  "mouseup": function () {},
  "mousemove": function () {},
  "mouseover": function () {},
  "mouseout": function () {},
  "mouseenter": function () {},
  "mouseleave": function () {},
  "change": function () {},
  "select": function () {},
  "submit": function () {},
  "keydown": function () {},
  "keypress": function () {},
  "keyup": function () {},
  "error": function () {},
  "contextmenu": function () {},
  "hover": function () {},
  "bind": function () {},
  "unbind": function () {},
  "delegate": function () {},
  "undelegate": function () {},
  "wrapAll": function () {},
  "wrapInner": function () {},
  "wrap": function () {},
  "unwrap": function () {},
  "serialize": function () {},
  "serializeArray": function () {},
  "ajaxStart": function () {},
  "ajaxStop": function () {},
  "ajaxComplete": function () {},
  "ajaxError": function () {},
  "ajaxSuccess": function () {},
  "ajaxSend": function () {},
  "offset": function () {},
  "position": function () {},
  "offsetParent": function () {},
  "scrollLeft": function () {},
  "scrollTop": function () {},
  "innerHeight": function () {},
  "height": function () {},
  "outerHeight": function () {},
  "innerWidth": function () {},
  "width": function () {},
  "outerWidth": function () {},
  "size": function () {},
  "andSelf": function () {},
  "accordion": function () {},
  "spinner" : function () {},
  "slider" : function () {}
};
jQuery.Event.prototype = {
  "isDefaultPrevented": function () {},
  "isPropagationStopped": function () {},
  "isImmediatePropagationStopped": function () {},
  "preventDefault": function () {},
  "stopPropagation": function () {},
  "stopImmediatePropagation": function () {}
};
jQuery.Tween.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cur": function () {},
  "run": function () {}
};
jQuery.fx.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cur": function () {},
  "run": function () {}
};