//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppGoTypeScript_X_Modulerization.PageAgent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Save", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Save : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scriptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stylesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string scripts {
            get {
                return this.scriptsField;
            }
            set {
                if ((object.ReferenceEquals(this.scriptsField, value) != true)) {
                    this.scriptsField = value;
                    this.RaisePropertyChanged("scripts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string styles {
            get {
                return this.stylesField;
            }
            set {
                if ((object.ReferenceEquals(this.stylesField, value) != true)) {
                    this.stylesField = value;
                    this.RaisePropertyChanged("styles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string page {
            get {
                return this.pageField;
            }
            set {
                if ((object.ReferenceEquals(this.pageField, value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PageAgent.PageServiceSoap")]
    public interface PageServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponse HelloWorld(WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponse> HelloWorldAsync(WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Obj from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePage", ReplyAction="*")]
        WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponse SavePage(WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePage", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponse> SavePageAsync(WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePage", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequestBody Body;
        
        public SavePageRequest() {
        }
        
        public SavePageRequest(WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebAppGoTypeScript_X_Modulerization.PageAgent.Save Obj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pageName;
        
        public SavePageRequestBody() {
        }
        
        public SavePageRequestBody(WebAppGoTypeScript_X_Modulerization.PageAgent.Save Obj, string site, string pageName) {
            this.Obj = Obj;
            this.site = site;
            this.pageName = pageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponseBody Body;
        
        public SavePageResponse() {
        }
        
        public SavePageResponse(WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SavePageResult;
        
        public SavePageResponseBody() {
        }
        
        public SavePageResponseBody(bool SavePageResult) {
            this.SavePageResult = SavePageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PageServiceSoapChannel : WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PageServiceSoapClient : System.ServiceModel.ClientBase<WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap>, WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap {
        
        public PageServiceSoapClient() {
        }
        
        public PageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponse WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap.HelloWorld(WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest inValue = new WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequestBody();
            WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponse retVal = ((WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponse> WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap.HelloWorldAsync(WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldResponse> HelloWorldAsync() {
            WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest inValue = new WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.PageAgent.HelloWorldRequestBody();
            return ((WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponse WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap.SavePage(WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest request) {
            return base.Channel.SavePage(request);
        }
        
        public bool SavePage(WebAppGoTypeScript_X_Modulerization.PageAgent.Save Obj, string site, string pageName) {
            WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest inValue = new WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequestBody();
            inValue.Body.Obj = Obj;
            inValue.Body.site = site;
            inValue.Body.pageName = pageName;
            WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponse retVal = ((WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap)(this)).SavePage(inValue);
            return retVal.Body.SavePageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponse> WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap.SavePageAsync(WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest request) {
            return base.Channel.SavePageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageResponse> SavePageAsync(WebAppGoTypeScript_X_Modulerization.PageAgent.Save Obj, string site, string pageName) {
            WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest inValue = new WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequest();
            inValue.Body = new WebAppGoTypeScript_X_Modulerization.PageAgent.SavePageRequestBody();
            inValue.Body.Obj = Obj;
            inValue.Body.site = site;
            inValue.Body.pageName = pageName;
            return ((WebAppGoTypeScript_X_Modulerization.PageAgent.PageServiceSoap)(this)).SavePageAsync(inValue);
        }
    }
}
